// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: 'production' | 'development';
	ALLOWED_ORIGIN: 'https://virtuescroll.com' | 'http://localhost:5173';
	DB: D1Database;
}
