// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: 'production' | 'development';
	ALLOWED_ORIGINS: { origins: ['https://virtuescroll.com', 'https://www.virtuescroll.com'] } | { origins: ['http://localhost:5173'] };
	DB: D1Database;
}
